/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagement;

import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author Shafin
 */
public class Student_List extends javax.swing.JFrame {

    /**
     * Creates new form Student_List
     */
    public Student_List() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        schoolmanagementPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("schoolmanagementPU").createEntityManager();
        studentInfoQuery = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery.getResultList();
        studentInfoQuery1 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery1.getResultList();
        studentInfoQuery2 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery2.getResultList();
        studentInfoQuery3 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery3.getResultList();
        studentInfoQuery4 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery4.getResultList();
        studentInfoQuery5 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery5.getResultList();
        studentInfoQuery6 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery6.getResultList();
        studentInfoQuery7 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList7 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery7.getResultList();
        studentInfoQuery8 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList8 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery8.getResultList();
        studentInfoQuery9 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList9 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery9.getResultList();
        studentInfoQuery10 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList10 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery10.getResultList();
        studentInfoQuery11 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList11 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery11.getResultList();
        studentInfoQuery12 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList12 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery12.getResultList();
        studentInfoQuery13 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList13 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery13.getResultList();
        studentInfoQuery14 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList14 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery14.getResultList();
        studentInfoQuery15 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT s FROM StudentInfo s");
        studentInfoList15 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentInfoQuery15.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Student_Table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student List");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, studentInfoList15, Student_Table);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${roll}"));
        columnBinding.setColumnName("Roll");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${firstName}"));
        columnBinding.setColumnName("First Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lastName}"));
        columnBinding.setColumnName("Last Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${class1}"));
        columnBinding.setColumnName("Class1");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${gender}"));
        columnBinding.setColumnName("Gender");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${year}"));
        columnBinding.setColumnName("Year");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${birthday}"));
        columnBinding.setColumnName("Birthday");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${moblile}"));
        columnBinding.setColumnName("Moblile");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${presentAddress}"));
        columnBinding.setColumnName("Present Address");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${parmanentAddress}"));
        columnBinding.setColumnName("Parmanent Address");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(Student_Table);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(846, 633));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MessageFormat header=new MessageFormat("Stident List");
       MessageFormat footer=new MessageFormat("Page{0,number,interger}");
       
           try {
               Student_Table.print(JTable.PrintMode.NORMAL, header, footer);
           } catch (PrinterException ex) {
               Logger.getLogger(Teacher_List.class.getName()).log(Level.SEVERE, null, ex);
           
       } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Student_Home g=new Student_Home();
       g.setVisible(true);
       dispose();
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Student_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.persistence.EntityManager schoolmanagementPUEntityManager;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList1;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList10;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList11;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList12;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList13;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList14;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList15;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList2;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList3;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList4;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList5;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList6;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList7;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList8;
    private java.util.List<schoolmanagement.StudentInfo> studentInfoList9;
    private javax.persistence.Query studentInfoQuery;
    private javax.persistence.Query studentInfoQuery1;
    private javax.persistence.Query studentInfoQuery10;
    private javax.persistence.Query studentInfoQuery11;
    private javax.persistence.Query studentInfoQuery12;
    private javax.persistence.Query studentInfoQuery13;
    private javax.persistence.Query studentInfoQuery14;
    private javax.persistence.Query studentInfoQuery15;
    private javax.persistence.Query studentInfoQuery2;
    private javax.persistence.Query studentInfoQuery3;
    private javax.persistence.Query studentInfoQuery4;
    private javax.persistence.Query studentInfoQuery5;
    private javax.persistence.Query studentInfoQuery6;
    private javax.persistence.Query studentInfoQuery7;
    private javax.persistence.Query studentInfoQuery8;
    private javax.persistence.Query studentInfoQuery9;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
