
package schoolmanagement;

import java.text.*;
import java.awt.print.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
public class Teacher_List extends javax.swing.JFrame {

    /**
     * Creates new form Teacher_List
     */
    public Teacher_List() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTextField1 = new javax.swing.JTextField();
        schoolmanagementPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("schoolmanagementPU").createEntityManager();
        teacherInfoQuery = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT t FROM TeacherInfo t");
        teacherInfoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : teacherInfoQuery.getResultList();
        teacherInfoQuery1 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT t FROM TeacherInfo t");
        teacherInfoList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : teacherInfoQuery1.getResultList();
        teacherInfoQuery2 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT t FROM TeacherInfo t");
        teacherInfoList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : teacherInfoQuery2.getResultList();
        teacherInfoQuery3 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT t FROM TeacherInfo t");
        teacherInfoList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : teacherInfoQuery3.getResultList();
        teacherInfoQuery4 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT t FROM TeacherInfo t");
        teacherInfoList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : teacherInfoQuery4.getResultList();
        teacherInfoQuery5 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT t FROM TeacherInfo t");
        teacherInfoList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : teacherInfoQuery5.getResultList();
        teacherInfoQuery6 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT t FROM TeacherInfo t");
        teacherInfoList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : teacherInfoQuery6.getResultList();
        teacherInfoQuery7 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT t FROM TeacherInfo t");
        teacherInfoList7 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : teacherInfoQuery7.getResultList();
        jSeparator1 = new javax.swing.JSeparator();
        teacherInfoQuery8 = java.beans.Beans.isDesignTime() ? null : schoolmanagementPUEntityManager.createQuery("SELECT t FROM TeacherInfo t");
        teacherInfoList8 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : teacherInfoQuery8.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Teacher_Table = new javax.swing.JTable();
        Print = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Teachers List");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, teacherInfoList8, Teacher_Table);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tid}"));
        columnBinding.setColumnName("Tid");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${firstname}"));
        columnBinding.setColumnName("Firstname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lastname}"));
        columnBinding.setColumnName("Lastname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${position}"));
        columnBinding.setColumnName("Position");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${birthday}"));
        columnBinding.setColumnName("Birthday");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${mobile}"));
        columnBinding.setColumnName("Mobile");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${sex}"));
        columnBinding.setColumnName("Sex");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${perAddress}"));
        columnBinding.setColumnName("Per Address");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${parAddress}"));
        columnBinding.setColumnName("Par Address");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(Teacher_Table);

        Print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Print.setForeground(new java.awt.Color(51, 51, 255));
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton1)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(jButton2)))
                        .addGap(0, 132, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Print)
                            .addComponent(jButton1))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton2)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(773, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
       MessageFormat header=new MessageFormat("Teacher List");
       MessageFormat footer=new MessageFormat("Page{0,number,interger}");
       
           try {
               Teacher_Table.print(JTable.PrintMode.NORMAL, header, footer);
           } catch (PrinterException ex) {
               Logger.getLogger(Teacher_List.class.getName()).log(Level.SEVERE, null, ex);
           
       } 
    }//GEN-LAST:event_PrintActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Teacher_Home go=new Teacher_Home();
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Print;
    private javax.swing.JTable Teacher_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.persistence.EntityManager schoolmanagementPUEntityManager;
    private java.util.List<schoolmanagement.TeacherInfo> teacherInfoList;
    private java.util.List<schoolmanagement.TeacherInfo> teacherInfoList1;
    private java.util.List<schoolmanagement.TeacherInfo> teacherInfoList2;
    private java.util.List<schoolmanagement.TeacherInfo> teacherInfoList3;
    private java.util.List<schoolmanagement.TeacherInfo> teacherInfoList4;
    private java.util.List<schoolmanagement.TeacherInfo> teacherInfoList5;
    private java.util.List<schoolmanagement.TeacherInfo> teacherInfoList6;
    private java.util.List<schoolmanagement.TeacherInfo> teacherInfoList7;
    private java.util.List<schoolmanagement.TeacherInfo> teacherInfoList8;
    private javax.persistence.Query teacherInfoQuery;
    private javax.persistence.Query teacherInfoQuery1;
    private javax.persistence.Query teacherInfoQuery2;
    private javax.persistence.Query teacherInfoQuery3;
    private javax.persistence.Query teacherInfoQuery4;
    private javax.persistence.Query teacherInfoQuery5;
    private javax.persistence.Query teacherInfoQuery6;
    private javax.persistence.Query teacherInfoQuery7;
    private javax.persistence.Query teacherInfoQuery8;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
